### ISSUE TITLE
[recommendation] What's your favourite command?

### ISSUE THREAD

**Issue by ravisankar-PIO** [NielsLiisberg/mums#1]
Hi @NielsLiisberg , this is such a cool idea to install third party open source packages in IBMi. I love this repo already!

While there are plethora of packages to install, I was wondering what are some of your favourite tools that are actually working.!?

Thanks,
Ravi.

**Comment by NielsLiisberg** [comment]
Hello Ravisankar

Especially I use these two all the time:

1) Image magic
2) Ghost script

Both real workhorses that IBM can not deliver by YUM because of licence
issues .

Always goto YUM first - if not there - then MUMS.

**Comment by ravisankar-PIO** [comment]
That's nice! I was curious to know what other packages could be useful for an IBMi developer outside of the yum. 

I used to play around with Imagemagick & Ghostscript for my personal projects. Never had an opportunity to utilize them professionally inside IBMi.

Thank you for the reply and have a good day!
